highbury/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('account.urls', namespace='account')),
    url(r'^board_free/', include('board_free.urls', namespace='board_free')),
    url(r'^board_football/', include('board_free.urls', namespace='board_football')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^arsenal/', include('arsenal.urls', namespace='arsenal')),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^pointshop/', include('pointshop.urls', namespace='pointshop')),

    url(r'^summernote/', include('django_summernote.urls')),
]

pointshop/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # point shop list page
    url(r'^list/$', views.point_list, name='list'),
    url(r'^list/(?P<category_id>[0-9]+)$', views.point_list, name='category_list'),
    # point shop detail page
    url(r'^detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/$', views.point_detail, name='detail'),
    # point shop recommend page
    url(r'^detail/recommend/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/$', views.product_recommend, name='product_recommend'),
    # point shop buy complete page
    url(r'^complete/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/(?P<order_num>[-\w]+)$', views.buy_complete, name='buy_complete'),
    # point shop delete page
    url(r'^delete/(?P<product_id>[0-9]+)/(?P<id>[0-9]+)/(?P<sort>[-\w]+)$', views.delete, name='delete'),
]

search/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
    url(r'^$', views.search, name='search'),
    url(r'^(?P<data>[-\w]+)$', views.search, name='search2'),
]

pointshop/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from django.utils.text import slugify
from tag.models import Tagging, Comment, Recommend


PLAYER_CHOICES = (
    ('player1', 'player1'),
    ('player2', 'player2'),
    ('player3', 'player3'),
    ('player4', 'player4'),
    ('player5', 'player5'),
    ('player6', 'player6'),
    ('player7', 'player7'),
    ('player8', 'player8'),
    ('player9', 'player9'),
    ('player10', 'player10'),
    ('player11', 'player11'),
)


STRATEGY_CHOICES = (
    ('strategy_4-2-3-1', 'strategy_4-2-3-1'),
    ('strategy_3-5-2', 'strategy_3-5-2'),
)


SATISFACTION_CHOICES = [(str(i),str(i)) for i in range(1,6)]


class Category(models.Model): # 카테고리
    name = models.CharField(max_length=255) # 상위 카테고리(ForeignKey)
    created = models.DateTimeField(default=timezone.now, db_index=True) # 카테고리 만들어진 날짜
    is_active = models.BooleanField(default=True) # 노출 여부

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('created', '-id')


class ProductCategory(models.Model): # 상품이 세로로 진열될 공간
    name = models.CharField(max_length=255) # 상품 카테고리 (세로 품목)
    category = models.ForeignKey(Category, related_name='sub_category') # 연관된 카테고리
    content = models.TextField(blank=True, null=True) # 상품 카테고리 내용
    created = models.DateTimeField(default=timezone.now, db_index=True) # 만들어진 시간
    is_active = models.BooleanField(default=True) # 노출 여부

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('created', '-id')


class Product(models.Model): # 상품 (만일 일반 상품으로 가게 될 경우 몇개 추가만 해주면 됨)
    title = models.CharField(max_length=100, null=True) # 상품 이름
    slug = models.SlugField(max_length=255, null=True, blank=True, allow_unicode=True) # slug

    main_category = models.ForeignKey(Category, null=True)
    category = models.ForeignKey(ProductCategory, related_name="product", db_index=True)  # 상품이 진열될 세로 위치
    point = models.IntegerField(default=0) # 상품에 책정된 포인트
    width = models.CharField(max_length=100, null=True) # 상품이 진열될 가로 위치
    created = models.DateTimeField(default=timezone.now) # 상품이 생성된 시간

    information = models.TextField() # 상품 정보
    image = models.ImageField(upload_to='product_image/') # 상품의 이미지
    buyer = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True) # 상품을 산 사람들 명단
    is_active = models.BooleanField(default=True) # 상품의 노출 상황

    tags = GenericRelation(Tagging)
    comments = GenericRelation(Comment)
    recommends = GenericRelation(Recommend)

    def __str__(self):
        return '{}. price {}point'.format(self.title, self.point)

    class Meta:
        ordering = ('-category', 'width')
        index_together = ('category', 'width')
        
    def save(self, *args, **kwargs):
        if not self.slug:
            make_slug = '{}-{}'.format(self.title, self.category)
            self.slug = slugify(make_slug, allow_unicode=True)
        super(Product, self).save(*args, **kwargs)
            

class DiscountManager(models.Manager):
    def get_queryset(self):
        return Discount.objects.filter(is_active=True, start_date__lt=timezone.now(), end_date__gt=timezone.now())

class Discount(models.Model): # 할인 행사
    name = models.CharField(max_length=150) # 할인 이름
    created = models.DateTimeField(default=timezone.now, db_index=True) # 할인 이름 생성 시간
    start_date = models.DateTimeField() # 할인 시작 시간
    end_date = models.DateTimeField() # 할인 마지막 시간
    discount_point = models.IntegerField(default=0) # 할인 확률
    is_active = models.BooleanField(default=True) # 할인 행사 노출 여부

    objects = models.Manager()
    active = DiscountManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created', '-id')


class UsePoint(models.Model):
    category = models.ForeignKey(Category) # 상위 카테고리
    product_category = models.ForeignKey(ProductCategory, null=True) # 하위 카테고리
    product = models.ForeignKey(Product) # 상품
    
    order_number = models.CharField(max_length=200, null=True, blank=True)
    buy_date = models.DateTimeField(default=timezone.now, db_index=True) # 포인트로 상품을 산 날짜
    user = models.ForeignKey(settings.AUTH_USER_MODEL) # 상품을 산 유저
    use_point = models.IntegerField(default=0) # 사용된 포인트

    def __str__(self):
        return '{} buy {}, spent {}point'.format(self.user, self.product, self.use_point)

    class Meta:
        ordering = ('buy_date', 'id')

    def save(self, *args, **kwargs):
        super(UsePoint, self).save(*args, **kwargs)
        if not self.order_number:
            self.order_number = 'point-order-' + str(1000000 + int(self.id))
            super(UsePoint, self).save(*args, **kwargs)


# 아직 미 구현
class FantasyLeague(models.Model):
    name = models.CharField(max_length=200) # 판타지 리그 이름
    user = models.ForeignKey(settings.AUTH_USER_MODEL) # 판타지 리그 유저
    created = models.DateTimeField(default=timezone.now) # 판타지 리그 만든 날
    position = models.CharField(max_length=10, choices=PLAYER_CHOICES) # 해당 선수의 포지션
    strategy = models.CharField(max_length=15, choices=STRATEGY_CHOICES, default='strategy_4-2-3-1') # 판타지 리그의 전술
    player = models.ForeignKey(Product) # 해당 선수

    def __str__(self):
        return '{} make {} fantasy league'.format(self.user, self.name)

    class Meta:
        ordering = ('user', 'name', 'position')
        index_together = ('user', 'name', 'position')

pointshop/forms.py
from django import forms

from .models import UsePoint


class UsePointForm(forms.ModelForm):
    class Meta:
        model = UsePoint
        fields = ('category', 'product_category', 'product', 'user', 'use_point')

pointshop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Avg
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse

from lib.paginator import paginator
from tag.models import Comment, Recommend

from .models import Product, UsePoint, Category
from .forms import UsePointForm


def point_list(request, category_id=None):
    category = None
    products = Product.objects.all()
    categories = Category.objects.filter(is_active=True).order_by('-created')

    if category_id:
        category = categories.get(id=category_id)
        if request.GET.get('sub_category'):
            products = products.filter(main_category=category_id, category=request.GET.get('sub_category'))
        else:
            products = products.filter(main_category=category_id)

    paginator = Paginator(products, 12)
    page = request.GET.get('page',1)
    try:
        products = paginator.page(page)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        products = paginator.page(paginator.num_pages)

    end_page = paginator.num_pages

    if request.is_ajax():
        return render(request, 'pointshop/list_ajax.jinja', {'products': products})

    return render(request, 'pointshop/list.jinja', {'products': products, 'end_page': end_page, 'categories': categories, 'select_menu': category})


@login_required
def point_detail(request, id, slug):
    point_ratio = None
    is_write = False

    # 상품의 리뷰와 댓글을 구함
    product = Product.objects.get(id=id, slug=slug)
    comments=product.comments.filter(sort='point-co').order_by('created',)
    reviews =product.comments.filter(sort='point-re').order_by('created',)
    sort_num = [len(reviews), len(comments)]
    # 평균 만족도를 구함
    if reviews:
        if request.user.nickname in reviews.values_list('user__nickname', flat=True):
            is_write = True
        point_ratio = reviews.aggregate(avg=Avg('satisfaction'))
    # paging 함수 (게시물 분리, 상품, 현재 페이지, 보여질 토탈 페이징)
    paging = paginator(reviews, request.GET, 'page', 'last', 3, 10)
    paging2 = paginator(comments, request.GET, 'sub_page', 'last', 20, 10)

    if request.method == 'POST':
        sort = request.POST.get('sort', None)
        if sort == 'buy_product':
            forms = UsePointForm(request.POST)
            if forms.is_valid():
                buy = forms.save(commit=False)
                product.buyer.add(request.user)
                buy.save()

                request.user.point.sort = 'spend'
                request.user.point.value = int(request.POST.get('use_point', None))
                request.user.point.save(update_fields=['sort', 'value', 'point'])

                return HttpResponseRedirect(reverse('pointshop:buy_complete', args=[product.id, product.slug, buy.order_number]))
        elif sort == 'write_comment':
            if not request.POST.get('content'):
                messages.error(request, '댓글에 아무것도 작성되어 있지 않습니다.')
                return HttpResponseRedirect(reverse('pointshop:detail', args=[product.id, product.slug]))
            else:
                Comment.objects.create(
                    content_object=product, user=request.user, sort='point-co', content=request.POST.get('content')
                )
                return HttpResponseRedirect(reverse('pointshop:detail', args=[product.id, product.slug]))
        else:
            review = request.POST.get('content')
            if not review:
                messages.error(request, '리뷰에 아무것도 작성되어 있지 않습니다.')
            if len(review) > 100:
                messages.error(request, '리뷰는 100글자 이하로 작성해주셔야 합니다.')
            elif not request.POST.get('satisfaction'):
                messages.error(request, '리뷰에는 만족도를 표시 해야 합니다.')
            else:
                Comment.objects.create(
                    user=request.user, sort='point-re', content=request.POST.get('content'),
                    satisfaction=request.POST.get('satisfaction'), content_object=product
                )
            return HttpResponseRedirect(reverse('pointshop:detail', args=[product.id, product.slug]))

    return render(request, 'pointshop/detail.jinja', {'product': product, 'point_ratio': point_ratio, 'reviews': paging, 'comments': paging2,
                                            'is_write': is_write, 'sort_num': sort_num})


def product_recommend(request, id, slug):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        product = Product.objects.get(id=id, slug=slug)
        if action == '추천':
            Recommend.objects.create(
                user=request.user, content_object=product
            )
        else:
            ct = ContentType.objects.get_for_model(product)
            recommend = Recommend.objects.get(content_type=ct, object_id=product.id, user=request.user)
            recommend.delete()
        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'false'})


def buy_complete(request, id, slug, order_num):
    order = UsePoint.objects.get(order_number=order_num)
    return render(request, 'pointshop/buy_complete.jinja', {'order': order})


def delete(request, product_id, id, sort):
    product = Product.objects.get(id=product_id)
    if sort == 'comment':
        try:
            comment = Comment.objects.get(id=id)
        except Comment.DoesNotExist:
            messages.error(request, '댓글이 삭제 된 상태입니다.')
        else:
            comment.delete()
    elif sort == 'review':
        try:
            review = Comment.objects.get(id=id)
        except Comment.DoesNotExist:
            messages.error(request, '리뷰가 삭제된 상태입니다.')
        else:
            review.delete()
    return HttpResponseRedirect(reverse('pointshop:detail', args=[product.id, product.slug]))

templates/pointshop/side_menu/pointshop_side_menu.jinja
{% extends 'base.jinja' %}
{% load custom_tags %}
{% load template_tags %}
{% block advertise %}
    <!-- 광고 영역 -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 card" style="padding:0;">
                {% sub_top_advertisements as top_advertisements %}
                {% for advertisement in top_advertisements %}
                    <a href="{{ advertisement.link }}">
                        <img class="img-fluid" src="{{ advertisement.banner.url }}" style="width:100%; height:200px;">
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock advertise %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top:5px; margin-bottom:100px;">
            <div class="col-lg-10 col-md-12">
                {% block left_side %}
                {% endblock left_side %}
            </div>
            <div class="col-lg-2 hidden-md-down" style="margin-top:70px;">
                {# community_right 광고가 들어가는 부분 #}
                <div class="row">
                    <div class="col-md-12 card" style="padding:0;">
                        {% community_right_advertisements as right_advertisements %}
                        {% for advertisement in right_advertisements %}
                            <a href="{{ advertisement.link }}">
                                <img class="rounded d-block img-fluid" src="{{ advertisement.banner.url }}" style="width:200px; height:200px;">
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-12 card">
                        <div class="row" style="text-align:center; padding:10px 0 7px 0; font-size:14px; border-bottom:1px solid #dadada; font-weight:bold;">
                            <div class="col-md-12">
                                최대 판매 상품
                            </div>
                        </div>
                        {% max_product as max_product %}
                        {% for product in max_product %}
                            <div class="row" style="text-align:center; padding:10px 0 7px 0; font-size:13px; {% if not forloop.last %}border-bottom:1px solid #dadada;{% endif %}">
                                <div class="col-md-12">
                                    {{ forloop.counter }}. <a href="{{ product.get_absolute_url }}">{{ product.title }} ({{ product.category }})</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-12 card">
                        <div class="row" style="text-align:center; padding:10px 0 7px 0; font-size:14px; border-bottom:1px solid #dadada; font-weight:bold;">
                            <div class="col-md-12">
                                인기 상품
                            </div>
                        </div>
                        {% popular_product as popular_product %}
                        {% for product in popular_product %}
                            <div class="row" style="text-align:center; padding:10px 0 7px 0; font-size:13px; {% if not forloop.last %}border-bottom:1px solid #dadada;{% endif %}">
                                <div class="col-md-12">
                                    {{ forloop.counter }}. <a href="{{ product.get_absolute_url }}">{{ product.title }} ({{ product.category }})</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-12 card">
                        <div class="row" style="text-align:center; padding:10px 0 7px 0; font-size:14px; font-weight:bold; border-bottom:1px solid #DADADA">
                            <div class="col-md-12">
                                인기 Tag
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12" style="margin:5px 0 8px 0;">
                                {% popular_tags as popular_tags %}
                                {% for tag in popular_tags %}
                                    <a class="btn" href="{% url 'search:search2' data=tag.0 %}" style="margin:1px 1px 1px 1px; font-size:12px; background-color:#2d2d2d; color:white; padding:3px 6px 3px 6px;">{{ tag.0 }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
